# https://cloud.google.com/appengine/docs/the-appengine-environments#comparing_high-level_features
# https://cloud.google.com/appengine/docs/standard

runtime: java17
instance_class: B1

manual_scaling:
  instances: 1

env_variables:
  TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
  TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
  TWILIO_API_KEY: ${TWILIO_API_KEY}
  TWILIO_API_SECRET: ${TWILIO_API_SECRET}
