# https://cloud.google.com/appengine/docs/the-appengine-environments#comparing_high-level_features
# https://cloud.google.com/appengine/docs/standard

runtime: java17
instance_class: B1

manual_scaling:
  instances: 1

env_variables:
  TWILIO_ACCOUNT_SID: "__TWILIO_ACCOUNT_SID__"
  TWILIO_AUTH_TOKEN: "__TWILIO_AUTH_TOKEN__"
  TWILIO_API_KEY: "__TWILIO_API_KEY__"
  TWILIO_API_SECRET: "__TWILIO_API_SECRET__"
